const cardsConfig = {
  actions1: [
    {
      id: '1.1',
      name: 'Cry',
      translation: 'Плакать',
      img: 'img/cry.jpg',
      audio: 'audio/cry.mp3',
    },
    {
      id: '1.2',
      name: 'Dance',
      translation: 'Танцевать',
      img: 'img/dance.jpg',
      audio: 'audio/dance.mp3',
    },
    {
      id: '1.3',
      name: 'Dive',
      translation: 'Нырять',
      img: 'img/dive.jpg',
      audio: 'audio/dive.mp3',
    },
    {
      id: '1.4',
      name: 'Draw',
      translation: 'Рисовать',
      img: 'img/draw.jpg',
      audio: 'audio/draw.mp3',
    },
    {
      id: '1.5',
      name: 'Fish',
      translation: 'Ловить рыбу',
      img: 'img/fish.jpg',
      audio: 'audio/fish.mp3',
    },
    {
      id: '1.6',
      name: 'Fly',
      translation: 'Летать',
      img: 'img/fly.jpg',
      audio: 'audio/fly.mp3',
    },
    {
      id: '1.7',
      name: 'Hug',
      translation: 'Обнимать',
      img: 'img/hug.jpg',
      audio: 'audio/hug.mp3',
    },
    {
      id: '1.8',
      name: 'Jump',
      translation: 'Прыгать',
      img: 'img/jump.jpg',
      audio: 'audio/jump.mp3',
    },
  ],
  actions2: [
    {
      id: '2.1',
      name: 'Open',
      translation: 'Открывать',
      img: 'img/open.jpg',
      audio: 'audio/open.mp3',
    },
    {
      id: '2.2',
      name: 'Play',
      translation: 'Играть',
      img: 'img/play.jpg',
      audio: 'audio/play.mp3',
    },
    {
      id: '2.3',
      name: 'Point',
      translation: 'Указывать',
      img: 'img/point.jpg',
      audio: 'audio/point.mp3',
    },
    {
      id: '2.4',
      name: 'Ride',
      translation: 'Ездить',
      img: 'img/ride.jpg',
      audio: 'audio/ride.mp3',
    },
    {
      id: '2.5',
      name: 'Run',
      translation: 'Бегать',
      img: 'img/run.jpg',
      audio: 'audio/run.mp3',
    },
    {
      id: '2.6',
      name: 'Sing',
      translation: 'Петь',
      img: 'img/sing.jpg',
      audio: 'audio/sing.mp3',
    },
    {
      id: '2.7',
      name: 'Skip',
      translation: 'Прыгать',
      img: 'img/skip.jpg',
      audio: 'audio/skip.mp3',
    },
    {
      id: '2.8',
      name: 'Swim',
      translation: 'Плавать',
      img: 'img/swim.jpg',
      audio: 'audio/swim.mp3',
    },
  ],
  actions3: [
    {
      id: '3.1',
      name: 'Argue',
      translation: 'Спорить',
      img: 'img/argue.jpg',
      audio: 'audio/argue.mp3',
    },
    {
      id: '3.2',
      name: 'Build',
      translation: 'Строить',
      img: 'img/build.jpg',
      audio: 'audio/build.mp3',
    },
    {
      id: '3.3',
      name: 'Carry',
      translation: 'Нести',
      img: 'img/carry.jpg',
      audio: 'audio/carry.mp3',
    },
    {
      id: '3.4',
      name: 'Catch',
      translation: 'Ловить',
      img: 'img/catch.jpg',
      audio: 'audio/catch.mp3',
    },
    {
      id: '3.5',
      name: 'Drive',
      translation: 'Водить',
      img: 'img/drive.jpg',
      audio: 'audio/drive.mp3',
    },
    {
      id: '3.6',
      name: 'Drop',
      translation: 'Падать',
      img: 'img/drop.jpg',
      audio: 'audio/drop.mp3',
    },
    {
      id: '3.7',
      name: 'Pull',
      translation: 'Тянуть',
      img: 'img/pull.jpg',
      audio: 'audio/pull.mp3',
    },
    {
      id: '3.8',
      name: 'Push',
      translation: 'Толкать',
      img: 'img/push.jpg',
      audio: 'audio/push.mp3',
    },
  ],

  emotions: [
    {
      id: '4.1',
      name: 'Sad',
      translation: 'Грустный',
      img: 'img/sad.jpg',
      audio: 'audio/sad.mp3',
    },
    {
      id: '4.2',
      name: 'Angry',
      translation: 'Cердитый',
      img: 'img/angry.jpg',
      audio: 'audio/angry.mp3',
    },
    {
      id: '4.3',
      name: 'Happy',
      translation: 'Cчастливый',
      img: 'img/happy.jpg',
      audio: 'audio/happy.mp3',
    },
    {
      id: '4.4',
      name: 'Tired',
      translation: 'Уставший',
      img: 'img/tired.jpg',
      audio: 'audio/tired.mp3',
    },
    {
      id: '4.5',
      name: 'Surprised',
      translation: 'Удивлённый',
      img: 'img/surprised.jpg',
      audio: 'audio/surprised.mp3',
    },
    {
      id: '4.6',
      name: 'Scared',
      translation: 'Испуганный',
      img: 'img/scared.jpg',
      audio: 'audio/scared.mp3',
    },
    {
      id: '4.7',
      name: 'Smile',
      translation: 'Улыбающийся',
      img: 'img/smile.jpg',
      audio: 'audio/smile.mp3',
    },
    {
      id: '4.8',
      name: 'Bored',
      translation: 'Скучающий',
      img: 'img/bored.jpg',
      audio: 'audio/bored.mp3',
    },
  ],
  colors: [
    {
      id: '5.1',
      name: 'Black',
      translation: 'Черный',
      img: 'img/black.jpg',
      audio: 'audio/en_black.mp3',
    },
    {
      id: '5.2',
      name: 'Green',
      translation: 'Зеленый',
      img: 'img/green.jpg',
      audio: 'audio/en_green.mp3',
    },
    {
      id: '5.3',
      name: 'Grey',
      translation: 'Cерый',
      img: 'img/grey.jpg',
      audio: 'audio/en_grey.mp3',
    },
    {
      id: '5.4',
      name: 'Orange',
      translation: 'Oранжевый',
      img: 'img/orange.jpg',
      audio: 'audio/en_orange.mp3',
    },
    {
      id: '5.5',
      name: 'Pink',
      translation: 'Pозовый',
      img: 'img/pink.jpg',
      audio: 'audio/en_pink.mp3',
    },
    {
      id: '5.6',
      name: 'Red',
      translation: 'Kрасный',
      img: 'img/red.jpg',
      audio: 'audio/en_red.mp3',
    },
    {
      id: '5.7',
      name: 'White',
      translation: 'Белый',
      img: 'img/white.jpg',
      audio: 'audio/en_white.mp3',
    },
    {
      id: '5.8',
      name: 'Yellow',
      translation: 'Желтый',
      img: 'img/yellow.jpg',
      audio: 'audio/en_yellow.mp3',
    },
  ],

  animals1: [
    {
      id: '6.1',
      name: 'Cat',
      translation: 'Kот',
      img: 'img/cat.jpg',
      audio: 'audio/cat.mp3',
    },
    {
      id: '6.2',
      name: 'Chick',
      translation: 'Цыплёнок',
      img: 'img/chick.jpg',
      audio: 'audio/chick.mp3',
    },
    {
      id: '6.3',
      name: 'Chicken',
      translation: 'Курица',
      img: 'img/chicken.jpg',
      audio: 'audio/chicken.mp3',
    },
    {
      id: '6.4',
      name: 'Dog',
      translation: 'Cобака',
      img: 'img/dog.jpg',
      audio: 'audio/dog.mp3',
    },
    {
      id: '6.5',
      name: 'Horse',
      translation: 'Лошадь',
      img: 'img/horse.jpg',
      audio: 'audio/horse.mp3',
    },
    {
      id: '6.6',
      name: 'Pig',
      translation: 'Свинья',
      img: 'img/pig.jpg',
      audio: 'audio/pig.mp3',
    },
    {
      id: '6.7',
      name: 'Rabbit',
      translation: 'Kролик',
      img: 'img/rabbit.jpg',
      audio: 'audio/rabbit.mp3',
    },
    {
      id: '6.8',
      name: 'Sheep',
      translation: 'Oвца',
      img: 'img/sheep.jpg',
      audio: 'audio/sheep.mp3',
    },
  ],

  animals2: [
    {
      id: '7.1',
      name: 'Bird',
      translation: 'Птица',
      img: 'img/bird.jpg',
      audio: 'audio/bird.mp3',
    },
    {
      id: '7.2',
      name: 'Fish',
      translation: 'Pыба',
      img: 'img/fish1.jpg',
      audio: 'audio/fish.mp3',
    },
    {
      id: '7.3',
      name: 'Frog',
      translation: 'Лягушка',
      img: 'img/frog.jpg',
      audio: 'audio/frog.mp3',
    },
    {
      id: '7.4',
      name: 'Giraffe',
      translation: 'Жираф',
      img: 'img/giraffe.jpg',
      audio: 'audio/giraffe.mp3',
    },
    {
      id: '7.5',
      name: 'Lion',
      translation: 'Лев',
      img: 'img/lion.jpg',
      audio: 'audio/lion.mp3',
    },
    {
      id: '7.6',
      name: 'Mouse',
      translation: 'Мышь',
      img: 'img/mouse.jpg',
      audio: 'audio/mouse.mp3',
    },
    {
      id: '7.7',
      name: 'Turtle',
      translation: 'Черепаха',
      img: 'img/turtle.jpg',
      audio: 'audio/turtle.mp3',
    },
    {
      id: '7.8',
      name: 'Dolphin',
      translation: 'Дельфин',
      img: 'img/dolphin.jpg',
      audio: 'audio/dolphin.mp3',
    },
  ],

  adjectives: [
    {
      id: '8.1',
      name: 'Big',
      translation: 'Большой',
      img: 'img/big.jpg',
      audio: 'audio/big.mp3',
    },
    {
      id: '8.2',
      name: 'Small',
      translation: 'Mаленький',
      img: 'img/small.jpg',
      audio: 'audio/small.mp3',
    },
    {
      id: '8.3',
      name: 'Fast',
      translation: 'Быстрый',
      img: 'img/fast.jpg',
      audio: 'audio/fast.mp3',
    },
    {
      id: '8.4',
      name: 'Slow',
      translation: 'Mедленный',
      img: 'img/slow.jpg',
      audio: 'audio/slow.mp3',
    },
    {
      id: '8.5',
      name: 'Friendly',
      translation: 'Дружелюбный',
      img: 'img/friendly.jpg',
      audio: 'audio/friendly.mp3',
    },
    {
      id: '8.6',
      name: 'Unfriendly',
      translation: 'Недружелюбный',
      img: 'img/unfriendly.jpg',
      audio: 'audio/unfriendly.mp3',
    },
    {
      id: '8.7',
      name: 'Young',
      translation: 'Mолодой',
      img: 'img/young.jpg',
      audio: 'audio/young.mp3',
    },
    {
      id: '8.8',
      name: 'Old',
      translation: 'Cтарый',
      img: 'img/old.jpg',
      audio: 'audio/old.mp3',
    },
  ],
};

const categories = [
  {
    id: '1',
    cards: cardsConfig.actions1,
    name: 'Actions (set 1)',
    img: 'img/dance.jpg',
  },
  {
    id: '2',
    cards: cardsConfig.actions2,
    name: 'Actions (set 2)',
    img: 'img/swim.jpg',
  },
  {
    id: '3',
    cards: cardsConfig.actions3,
    name: 'Actions (set 3)',
    img: 'img/drop.jpg',
  },
  {
    id: '4',
    cards: cardsConfig.emotions,
    name: 'Emotions',
    img: 'img/smile.jpg',
  },
  {
    id: '5',
    cards: cardsConfig.colors,
    name: 'Colors',
    img: 'img/orange.jpg',
  },
  {
    id: '6',
    cards: cardsConfig.animals1,
    name: 'Animals (set 1)',
    img: 'img/cat.jpg',
  },
  {
    id: '7',
    cards: cardsConfig.animals2,
    name: 'Animals (set 2)',
    img: 'img/frog.jpg',
  },
  {
    id: '8',
    cards: cardsConfig.adjectives,
    name: 'Adjectives',
    img: 'img/friendly.jpg',
  },
];

export default { cardsConfig, categories };
